before_install:

  # Download xmllint for XML validation
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-utils

  # Download the MPD catalog schema and dependencies
  - wget -r --no-parent --reject "index.html*" -nH -Pdownload https://reference.niem.gov/niem/specification/model-package-description/3.0.1/xsd-mpd-catalog/

script:

  # Validate the IEPD extension schema
  - xmllint --schema http://www.w3.org/2001/XMLSchema.xsd --noout base-xsd/extension/extension.xsd

  # Validate all sample instances against the extension schema
  - xmllint --schema base-xsd/extension/extension.xsd --noout iep-sample/*.xml

  # Validate the MPD catalog file against the MPD catalog schema downloaded above
  - xmllint --schema download/niem/specification/model-package-description/3.0.1/xsd-mpd-catalog/mpd-catalog-3.0.xsd --noout mpd-catalog.xml
